version: '3.8'

networks:
  docker-network:
    driver: bridge

services:
  dataloader:
    image: crypto-investment-recommendation-service:1.0.1-SNAPSHOT
    container_name: cirs_dataloader
    restart: always
    networks: [docker-network]
  api:
    image: crypto-investment-recommendation-service:1.0.1-SNAPSHOT
    container_name: cirs_rest_api
    ports:
      - "8080:8080"
    restart: always
    networks: [docker-network]
